import type { BeatModule } from './beat';
import { beat1 } from './Beat1';
import { beat2 } from './Beat2';
import { beat3 } from './Beat3';
import { beat4 } from './Beat4';
import { beat5 } from './Beat5';
import { beat6 } from './Beat6';
import { beat7 } from './Beat7';
import { beat8 } from './Beat8';
export const MODULES: BeatModule[] = [beat1, beat2, beat3, beat4, beat5, beat6, beat7, beat8];
