#!/usr/bin/env python3
"""Builds rules/no-unstepped-infinite-animation.yml — edit HERE, then run
`python3 scripts/ast-grep/generators/no-unstepped-infinite-animation.py`
(Plan B t6a review fix, 2026-09-16). The regexes are generated because
ast-grep's regex engine (Rust) has no lookaround: "a bracket with no `steps(` whose
keyframe name is not exempt" must be written as explicit complement languages."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# The rig-* body loops left CSS on 2026-09-26 (MascotRig draws them at 30 fps,
# rig-body-loop.ts), so they are no longer exempt: a smooth rig loop is new again.
EXEMPT = ['comp-twinkle', 'comp-spin', 'comp-pulse', 'comp-bob', 'mascot-comp-float',
          'buddy-breathe', 'model-load-sweep']


def cls(excl):
    """A negated character class excluding the given literal chars."""
    return '[^' + ''.join('\\' + c if c in '\\]^-[' else c for c in excl) + ']'


def avoid_steps(stop):
    """Strings over [^stop] that never contain `steps(` (DFA for the word, turned
    into a regex: items that return to the start state, then an optional tail)."""
    s = lambda extra: cls(stop + extra)
    loop = '(?:s|ts|tes|tepss)'
    exit_ = f'(?:{s("st")}|t{s("es")}|te{s("ps")}|tep{s("s")}|teps{s("(s")})'
    return f'(?:{s("s")}|s{loop}*{exit_})*(?:s{loop}*(?:t|te|tep|teps)?)?'


def not_in(words, stop):
    """Strings over [^stop] that are not exactly one of `words` (trie complement)."""
    trie = {}
    for w in words:
        node = trie
        for ch in w:
            node = node.setdefault(ch, {})
        node['$'] = True
    alts = []
    def walk(node, path):
        kids = [k for k in node if k != '$']
        alts.append(re.escape(path) + cls(stop + ''.join(kids)) + cls(stop) + '*')
        if '$' not in node:
            alts.append(re.escape(path))
        for k in kids:
            walk(node[k], path + k)
    walk(trie, '')
    return '(?:' + '|'.join(alts) + ')'


C = avoid_steps(']')
NAME = not_in(EXEMPT, '_]')
# One offending Tailwind bracket: non-exempt name, then `_…infinite…` with no steps(.
BRACKET = r'animate-\[' + NAME + '_' + C + 'infinite' + C + r'\]'
# One offending inline value: `animation: '…infinite…'` with no steps( inside the quotes.
CQ = avoid_steps("'")
INLINE = r"animation:\s*'" + CQ + 'infinite' + CQ + "'"


def q(rx):
    return '"' + rx.replace('\\', '\\\\').replace('"', '\\"') + '"'


YAML = f'''# GENERATED — edit scripts/ast-grep/generators/no-unstepped-infinite-animation.py,
# then run it (`python3 scripts/ast-grep/generators/no-unstepped-infinite-animation.py`).
# check.sh runs this generator with --check and fails loudly if this file has
# drifted from what it would produce (review round 2, 2026-09-16).
id: no-unstepped-infinite-animation
language: tsx
severity: error
message: >-
  A NEW `infinite` animation in a renderer component — whether an inline
  `animation: '...'` style or a Tailwind `animate-[name_..._infinite]`
  arbitrary value — must carry `steps(...)` timing, or it repaints at the
  display's full refresh rate for as long as it's on screen (measured
  ~1.5-1.9ms of CPU per frame, ~29% of one core at 180Hz, for a single
  pulsing dot — 2026-07-30 idle-CPU investigation). `will-change`/layer
  promotion does NOT fix this (measured 29.8% -> 27.8%, still useless).
note: |
  Invariant source: tests/animation-frame-budget.test.ts (Plan B, 2026-09-16;
  the two SWEEP cases "bans NEW inline infinite animations without steps
  timing in components" and "bans Tailwind arbitrary-value infinite
  animations without steps()"), which read every .tsx under
  src/renderer/components (test files included) as RAW text.
  FIX (review of t6a, 2026-09-16), to match that scope exactly:
  - Inline: the retired regex was `animation:\\s*'([^']*infinite[^']*)'` —
    only an unquoted key ending in `animation` directly followed by a
    SINGLE-quoted string (a ternary, a double-quoted or a template value was
    never checked, so it is not checked here). Raw text also meant comments
    and strings spelling that shape counted.
  - Tailwind: every `animate-[…]` bracket is judged on its own — the old
    loop took each match separately — so an exempt or stepped bracket beside
    an unstepped one no longer hides it. A class string split by `${{…}}` is
    matched on the whole template_string (the raw text the old regex saw);
    comments count too.
  - `.test.tsx` files are no longer ignored (the old walk read them).
  The regexes are generated by
  scripts/ast-grep/generators/no-unstepped-infinite-animation.py (edit there): ast-grep's Rust
  regex has no lookaround, so "no `steps(` inside the quotes/brackets" and
  "keyframe name not in EXCEPTIONS" are spelled as complement languages.
  Known gap: a keyframe whose NAME itself contains `infinite` (with nothing
  infinite after the first `_`) is not matched.
  EXCEPTIONS mirrors the retired test's ANIMATION_EXCEPTIONS table
  ({', '.join(EXEMPT)}): character motion and visibility-gated
  theme-companion animations deliberately NOT stepped. The CSS sweep in
  tests/animation-css-budget.test.ts keeps the same table.
files:
  - "**/src/renderer/components/**/*.tsx"
  - "**/fixtures/no-unstepped-infinite-animation.tsx"
rule:
  any:
    # Inline style: `animation: '…infinite…'` (single-quoted), no steps(.
    - kind: string
      regex: {q("^'" + CQ + 'infinite' + CQ + "'$")}
      inside:
        kind: pair
        has: {{ field: key, kind: property_identifier, regex: "animation$" }}
    # The same shape spelled inside a comment or another string (raw-text scope).
    - any:
        - kind: comment
        - kind: string_fragment
      regex: {q(INLINE)}
    # Tailwind arbitrary value, judged per bracket.
    - any:
        - kind: string_fragment
        - kind: comment
      regex: {q(BRACKET)}
    # …and across `${{…}}` in a template literal, when no single fragment holds it.
    - kind: template_string
      regex: {q(BRACKET)}
      # A nested string (or template) holding a whole offending bracket reports
      # itself; the outer template's text contains it too, so skip it then.
      not:
        has:
          stopBy: end
          any:
            - kind: string_fragment
            - kind: template_string
          regex: {q(BRACKET)}
'''

RULE_PATH = f'{ROOT}/rules/no-unstepped-infinite-animation.yml'

# Self-check the generated regexes with Python's engine (same syntax subset).
def selfcheck() -> int:
    b = re.compile(BRACKET)
    cases = {
        'animate-[version-glow_2s_ease_infinite]': True,
        'animate-[version-glow_2s_steps(16)_infinite]': False,
        'animate-[buddy-breathe_2s_ease_infinite]': False,
        'animate-[buddy-breathe_2s_steps(4)_infinite] animate-[glow_1s_infinite]': True,
        'animate-[buddy-breathex_2s_infinite]': True,
        # No longer exempt (2026-09-26): the rig body loops are drawn at 30 fps by MascotRig.
        'animate-[rig-breathe_2s_ease_infinite]': True,
        'animate-[rig_2s_infinite]': True,
        'animate-[glow_2s_ssteps(3)_infinite]': False,
        'animate-[glow_2s_stepss_infinite]': True,
        'animate-[glow_2s_steps_(3)_infinite]': True,
        'animate-[glow_2s_ease]': False,
        'animate-[${x}_infinite]': True,
        'animate-[model-load-sweep_1s_infinite]': False,
        'animate-[glow_1s_infinite_steps(2)]': False,
    }
    bad = 0
    for t, want in cases.items():
        got = bool(b.search(t))
        if got != want:
            bad += 1
            print('BRACKET MISMATCH', t, got, want)
    i = re.compile(INLINE)
    for t, want in {"animation: 'glow 2s ease infinite'": True, "animation: 'glow 2s steps(8) infinite'": False,
                    "animation: 'a 1s both'": False, "animation:'x infinite steps(2)'": False}.items():
        if bool(i.search(t)) != want:
            bad += 1
            print('INLINE MISMATCH', t)
    return bad


if __name__ == '__main__':
    import sys
    bad = selfcheck()
    if bad:
        print('selfcheck bad', bad, file=sys.stderr)
        sys.exit(1)
    if '--check' in sys.argv:
        # WHY (review round 2, 2026-09-16): a hand-edit to the generated YAML
        # (or a generator edit nobody re-ran) drifts silently — check.sh wires
        # this in so drift fails the same way a rule with no fixture does.
        current = open(RULE_PATH).read() if os.path.exists(RULE_PATH) else None
        if current != YAML:
            print(f'DRIFT: {RULE_PATH} does not match this generator\'s output.', file=sys.stderr)
            print('  Run: python3 scripts/ast-grep/generators/no-unstepped-infinite-animation.py', file=sys.stderr)
            sys.exit(1)
        print('OK — no-unstepped-infinite-animation.yml matches the generator')
    else:
        open(RULE_PATH, 'w').write(YAML)
        print('selfcheck bad', bad)
