// scripts/perf-lab/tests/screenshots.test.mjs — proves the pixel-diff engine that enforces
// the perf lab's "zero visible UX change" rule. Every fixture PNG is generated by the module
// itself in headless Chrome, so the rig needs no PNG library and no checked-in binaries.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { diffPngs, renderTestPng, compareScreens, capture, withHeadlessChrome, FREEZE, UNFREEZE, SCREEN_NAMES } from '../screenshots.mjs';

test('diffPngs reports WHERE the change is, and names a whole-frame vertical shift', async () => {
  // A DIFF percentage alone cannot be acted on: 2.21% on the welcome screen was a
  // 15px shift from a header appearing (another PR's UI change), not a regression
  // in the change under test. Finding that out by hand cost real time on
  // 2026-08-28; the differ says it now.
  const dir = mkdtempSync(join(tmpdir(), 'shot-shift-'));
  const a = join(dir, 'a.png'), b = join(dir, 'b.png');
  const bg = { x: 0, y: 0, w: 200, h: 200, color: '#ffffff' };
  writeFileSync(a, await renderTestPng(200, 200, [bg, { x: 20, y: 40, w: 160, h: 60, color: '#101820' }]));
  // The same content, 15px lower — a header appeared above it.
  writeFileSync(b, await renderTestPng(200, 200, [bg, { x: 20, y: 55, w: 160, h: 60, color: '#101820' }]));
  const r = await diffPngs(a, b);
  assert.equal(r.shift?.dy, 15, 'should recognise the 15px downward shift');
  assert.ok(r.box && r.box.h > 0, 'should report a bounding box for the change');
  assert.ok(r.box.y >= 40 && r.box.y <= 41, `box should start at the moved block, got y=${r.box?.y}`);

  // A LOCAL change is not a shift, and must not be reported as one.
  const c = join(dir, 'c.png');
  writeFileSync(c, await renderTestPng(200, 200, [bg, { x: 20, y: 40, w: 160, h: 60, color: '#101820' }, { x: 5, y: 5, w: 12, h: 12, color: '#ff0000' }]));
  const local = await diffPngs(a, c);
  assert.equal(local.shift, null, 'a local change must not be labelled a shift');
  assert.deepEqual({ x: local.box.x, y: local.box.y }, { x: 5, y: 5 });
});

test('diffPngs counts changed pixels (needs google-chrome-stable)', async () => {
  const d = mkdtempSync(join(tmpdir(), 'pl-shots-'));
  const a = join(d, 'a.png'), b = join(d, 'b.png');
  writeFileSync(a, await renderTestPng(100, 100, [{ x: 0, y: 0, w: 100, h: 100, color: '#fff' }]));
  writeFileSync(b, await renderTestPng(100, 100, [{ x: 0, y: 0, w: 100, h: 100, color: '#fff' }, { x: 0, y: 0, w: 10, h: 10, color: '#000' }]));
  const r = await diffPngs(a, b);
  assert.equal(r.total, 10000); assert.equal(r.differing, 100); assert.equal(r.pct, 1);
  assert.equal((await diffPngs(a, a)).differing, 0);
});

test('identical images report pct 0 and pass the gate', async () => {
  const d = mkdtempSync(join(tmpdir(), 'pl-shots-same-'));
  const a = join(d, 'a.png');
  writeFileSync(a, await renderTestPng(40, 40, [{ x: 0, y: 0, w: 40, h: 40, color: '#336699' }]));
  const r = await diffPngs(a, a);
  assert.equal(r.differing, 0);
  assert.equal(r.pct, 0);
  assert.equal(r.sizeMatch, true);
});

test('a sub-threshold colour shift counts as zero differing pixels', async () => {
  // WHY: the >16-per-channel tolerance exists so font anti-aliasing and GPU-vs-CPU
  // rasterisation jitter do not fail an otherwise pixel-identical build.
  const d = mkdtempSync(join(tmpdir(), 'pl-shots-tol-'));
  const a = join(d, 'a.png'), b = join(d, 'b.png'), c = join(d, 'c.png');
  // 0x80 -> 0x8F is a delta of 15 on every channel: under tolerance, must be invisible.
  writeFileSync(a, await renderTestPng(50, 50, [{ x: 0, y: 0, w: 50, h: 50, color: '#808080' }]));
  writeFileSync(b, await renderTestPng(50, 50, [{ x: 0, y: 0, w: 50, h: 50, color: '#8f8f8f' }]));
  const under = await diffPngs(a, b);
  assert.equal(under.differing, 0, 'delta 15 must be under the 16 tolerance');
  // 0x80 -> 0x91 is a delta of 17 on every channel: over tolerance, must be counted.
  writeFileSync(c, await renderTestPng(50, 50, [{ x: 0, y: 0, w: 50, h: 50, color: '#919191' }]));
  const over = await diffPngs(a, c);
  assert.equal(over.differing, 2500, 'delta 17 must be over the 16 tolerance');
  assert.equal(over.pct, 100);
});

test('different dimensions are reported explicitly, not silently padded away', async () => {
  // WHY: the diff pads both images onto a max(w) x max(h) canvas. Padding is transparent,
  // so a size change over DARK content would compare RGB-equal and report 0% — a resized
  // window would sail through the gate. Alpha is part of the comparison to stop that, and
  // sizeMatch:false is surfaced so the caller can reject on the size change alone.
  const d = mkdtempSync(join(tmpdir(), 'pl-shots-dim-'));
  const shortWhite = join(d, 'short-white.png'), tallWhite = join(d, 'tall-white.png');
  writeFileSync(shortWhite, await renderTestPng(100, 100, [{ x: 0, y: 0, w: 100, h: 100, color: '#fff' }]));
  writeFileSync(tallWhite, await renderTestPng(100, 120, [{ x: 0, y: 0, w: 100, h: 120, color: '#fff' }]));
  const r = await diffPngs(shortWhite, tallWhite);
  assert.equal(r.total, 12000, 'canvas is max(w) x max(h)');
  assert.equal(r.differing, 2000, 'the 100x20 band that only one image covers');
  assert.equal(r.pct, 16.67);
  assert.equal(r.sizeMatch, false);
  assert.deepEqual(r.a, { width: 100, height: 100 });
  assert.deepEqual(r.b, { width: 100, height: 120 });

  // The dark-content case is the one plain RGB comparison would have missed entirely.
  const shortBlack = join(d, 'short-black.png'), tallBlack = join(d, 'tall-black.png');
  writeFileSync(shortBlack, await renderTestPng(100, 100, [{ x: 0, y: 0, w: 100, h: 100, color: '#000' }]));
  writeFileSync(tallBlack, await renderTestPng(100, 120, [{ x: 0, y: 0, w: 100, h: 120, color: '#000' }]));
  const dark = await diffPngs(shortBlack, tallBlack);
  assert.equal(dark.differing, 2000, 'transparent padding must differ from opaque black');
  assert.equal(dark.sizeMatch, false);
});

test('pct rounds to 2dp, so one changed pixel in a full-size screenshot passes the gate', async () => {
  // WHY: 1 / (1600*1000) = 0.0000625%, which rounds to 0.00 and passes `pct <= 0.05`.
  // That is intended — the gate exists to catch visible regressions, and a lone pixel is
  // below the rounding floor. The raw `differing` count rides along in the result for
  // anyone who wants to audit a "0%" pass.
  const d = mkdtempSync(join(tmpdir(), 'pl-shots-round-'));
  const a = join(d, 'a.png'), b = join(d, 'b.png');
  writeFileSync(a, await renderTestPng(1600, 1000, [{ x: 0, y: 0, w: 1600, h: 1000, color: '#fff' }]));
  writeFileSync(b, await renderTestPng(1600, 1000, [{ x: 0, y: 0, w: 1600, h: 1000, color: '#fff' }, { x: 0, y: 0, w: 1, h: 1, color: '#000' }]));
  const r = await diffPngs(a, b);
  assert.equal(r.total, 1600000);
  assert.equal(r.differing, 1, 'the changed pixel IS counted');
  assert.equal(r.pct, 0, 'but rounds below the 2dp floor');
  assert.ok(r.pct <= 0.05, 'and therefore passes the keep/reject gate');
});

test('compareScreens grades a directory pair against the 0.05% gate', async () => {
  const base = mkdtempSync(join(tmpdir(), 'pl-base-'));
  const cand = mkdtempSync(join(tmpdir(), 'pl-cand-'));
  const white = await renderTestPng(200, 100, [{ x: 0, y: 0, w: 200, h: 100, color: '#fff' }]);
  // `welcome` is byte-identical; `settings-open` gains a 20x20 block = 400/20000 = 2%.
  writeFileSync(join(base, 'welcome.png'), white);
  writeFileSync(join(cand, 'welcome.png'), white);
  writeFileSync(join(base, 'settings-open.png'), white);
  writeFileSync(join(cand, 'settings-open.png'), await renderTestPng(200, 100, [{ x: 0, y: 0, w: 200, h: 100, color: '#fff' }, { x: 0, y: 0, w: 20, h: 20, color: '#000' }]));
  const out = await compareScreens(base, cand, ['welcome', 'settings-open']);
  assert.equal(out.welcome.pct, 0);
  assert.equal(out.welcome.pass, true);
  assert.equal(out['settings-open'].pct, 2);
  assert.equal(out['settings-open'].pass, false);
  assert.equal(out['settings-open'].differing, 400);
});

test('FREEZE kills CSS animations and transitions; UNFREEZE restores them', async () => {
  // WHY: a screenshot taken mid-animation differs from the same UI at rest, which would
  // make the parity gate flap. This proves the freeze style really lands on the element.
  const probe = await withHeadlessChrome(async (cdp) => {
    const setup = `(() => {
      const st = document.createElement('style');
      st.textContent = '@keyframes spin{from{opacity:0}to{opacity:1}} #probe{animation:spin 5s infinite;transition:opacity 5s;caret-color:red}';
      document.head.appendChild(st);
      const d = document.createElement('div'); d.id = 'probe'; document.body.appendChild(d);
      return true;
    })()`;
    const read = `(() => { const c = getComputedStyle(document.getElementById('probe'));
      return { animation: c.animationName, transition: c.transitionDuration, caret: c.caretColor, frozenStyle: !!document.getElementById('__perf-freeze') }; })()`;
    await cdp.evaluate(setup);
    const before = await cdp.evaluate(read);
    await cdp.evaluate(FREEZE);
    const during = await cdp.evaluate(read);
    await cdp.evaluate(UNFREEZE);
    const after = await cdp.evaluate(read);
    return { before, during, after };
  });
  assert.equal(probe.before.animation, 'spin');
  assert.equal(probe.before.frozenStyle, false);

  assert.equal(probe.during.animation, 'none', 'freeze must stop the animation');
  assert.equal(probe.during.transition, '0s', 'freeze must stop transitions');
  assert.equal(probe.during.caret, 'rgba(0, 0, 0, 0)', 'freeze must hide the blinking caret');
  assert.equal(probe.during.frozenStyle, true);

  assert.equal(probe.after.animation, 'spin', 'unfreeze must restore the animation');
  assert.equal(probe.after.frozenStyle, false, 'unfreeze must remove the style element');
});

test('a missing Chrome binary fails loudly with the port and the binary named', async () => {
  // WHY: the draft did `target.webSocketDebuggerUrl` on an undefined target, so a Chrome
  // that never came up surfaced as `TypeError: Cannot read properties of undefined`.
  await assert.rejects(
    () => withHeadlessChrome(async () => 'unreachable', { binary: 'google-chrome-does-not-exist', port: 9556, timeoutMs: 1500 }),
    (err) => {
      assert.match(err.message, /google-chrome-does-not-exist/, 'names the binary it tried');
      assert.match(err.message, new RegExp(String(9556)), 'names the debugging port');
      assert.match(err.message, /ENOENT|spawn/, 'carries the real OS-level failure, not a guess');
      return true;
    },
  );
});

test('overlapping runs never share a browser, so none of them can hang', async () => {
  // WHY: with the draft's fixed port + single shared profile, a second run silently attached to
  // the first run's Chrome and hung forever when that run tore it down (cdp.mjs never rejects
  // in-flight requests on socket close). Each launch now gets its own port and profile.
  const ports = await Promise.all([0, 1, 2, 3].map(() =>
    withHeadlessChrome(async (cdp) => {
      // Hold the browser long enough that all four overlap, then prove it is still alive.
      await new Promise((r) => setTimeout(r, 1200));
      return cdp.evaluate('location.href');
    }),
  ));
  assert.equal(ports.length, 4);
  for (const href of ports) assert.equal(href, 'about:blank', 'every run kept a live browser of its own');

  // And the killer ordering: an early finisher must not take a later one down with it.
  const slow = withHeadlessChrome(async (cdp) => {
    await new Promise((r) => setTimeout(r, 2500));
    return cdp.evaluate('40 + 2');
  });
  await new Promise((r) => setTimeout(r, 400));
  await withHeadlessChrome(async (cdp) => cdp.evaluate('1'));   // starts later, finishes first
  assert.equal(await slow, 42, 'the slow run survived the fast run tearing its Chrome down');
});

test('each run removes its throwaway Chrome profile', async () => {
  // WHY: SIGKILL is async and a dying Chrome recreates profile files, so an immediate rmSync
  // silently left an 8 KB dir behind on every single launch. Cleanup now waits for the exit.
  const before = readdirSync(tmpdir()).filter((f) => f.startsWith('perf-lab-diff-')).length;
  await withHeadlessChrome(async (cdp) => cdp.evaluate('1'));
  await withHeadlessChrome(async (cdp) => cdp.evaluate('1'));
  const after = readdirSync(tmpdir()).filter((f) => f.startsWith('perf-lab-diff-')).length;
  assert.equal(after, before, 'no orphaned profile directories in the OS temp dir');
});

test('an explicitly supplied profile is left alone', async () => {
  // WHY: only profiles the module minted itself are deleted — a caller-pinned one is theirs.
  const mine = mkdtempSync(join(tmpdir(), 'pl-keepme-'));
  await withHeadlessChrome(async (cdp) => cdp.evaluate('1'), { profile: mine });
  assert.equal(existsSync(mine), true);
  rmSync(mine, { recursive: true, force: true });
});

test('capture writes a PNG and always removes the freeze style, even when it fails', async () => {
  // WHY: `capture` runs against the LIVE app. A freeze style left injected after a failed
  // screenshot would silently disable animations for the rest of the measurement run.
  await withHeadlessChrome(async (cdp) => {
    await cdp.send('Page.enable');
    const out = mkdtempSync(join(tmpdir(), 'pl-cap-'));

    // Give the page real, painted content. capture() now REFUSES to save a frame
    // that has not reached first-contentful-paint (a blank shot silently passes the
    // parity gate against another blank shot), so a bare about:blank is rejected
    // by design — this test must supply something to paint.
    await cdp.evaluate(`document.body.innerHTML = '<h1 style="color:#fff;background:#123">perf-lab capture fixture — painted content</h1>'`);
    await cdp.evaluate('new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))');

    const p = await capture({ cdp }, out, 'welcome');
    assert.equal(p, join(out, 'welcome.png'));
    assert.equal(readFileSync(p).subarray(1, 4).toString(), 'PNG', 'a real PNG landed on disk');
    assert.equal(await cdp.evaluate("!!document.getElementById('__perf-freeze')"), false, 'unfrozen on success');

    // Now make the screenshot itself fail and prove the style still comes back off.
    const broken = { cdp: { evaluate: cdp.evaluate, send: async (m, params) => {
      if (m === 'Page.captureScreenshot') throw new Error('boom');
      return cdp.send(m, params);
    } } };
    await assert.rejects(() => capture(broken, out, 'welcome'), /boom/);
    assert.equal(await cdp.evaluate("!!document.getElementById('__perf-freeze')"), false, 'unfrozen on failure too');
  });
});

test('capture refuses to save a frame that never painted', async () => {
  // The regression this pins: `welcome` was shot before first-contentful-paint and
  // landed as a 4.5 KB blank rectangle, which the parity gate then compared against
  // another blank rectangle and passed.
  await withHeadlessChrome(async (cdp) => {
    await cdp.send('Page.enable');
    const out = mkdtempSync(join(tmpdir(), 'pl-blank-'));
    await cdp.evaluate("document.body.innerHTML = ''");
    await assert.rejects(
      () => capture({ cdp }, out, 'welcome', { timeoutMs: 1500 }),
      /had not painted|Refusing to save a blank frame/);
    assert.equal(existsSync(join(out, 'welcome.png')), false, 'no blank PNG was written');
  });
});

test('compareScreens defaults to SCREEN_NAMES when no list is passed', async () => {
  const base = mkdtempSync(join(tmpdir(), 'pl-def-base-'));
  const cand = mkdtempSync(join(tmpdir(), 'pl-def-cand-'));
  const white = await renderTestPng(20, 20, [{ x: 0, y: 0, w: 20, h: 20, color: '#fff' }]);
  for (const n of SCREEN_NAMES) { writeFileSync(join(base, `${n}.png`), white); writeFileSync(join(cand, `${n}.png`), white); }
  const out = await compareScreens(base, cand);
  assert.deepEqual(Object.keys(out).sort(), [...SCREEN_NAMES].sort());
  for (const n of SCREEN_NAMES) assert.equal(out[n].pass, true);
});
